  spring:
    application:
      name: fund-transfer-service

    datasource:
      url: jdbc:postgresql://localhost:5432/fund_transfer_db
      username: postgres
      password: P@ssw0rd
      driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
  #      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

    liquibase:
      enabled: true
      change-log: classpath:/db/changelog/db.changelog-master.xml

  server:
    port: 8081

  ftp:
    lock-strategy: MEMORY

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

  jwt:
    secret: SuperSecureKeyThatIsAtLeast64CharactersLongToAvoidWeakKeyException1234567890
    expiration: 86400000

  logging:
    level:
      org.springframework: DEBUG
      com.ftp.fundtransferservice: DEBUG
    file:
      name: logs/application.log
      max-size: 10MB
      max-history: 30